### ISSUE TITLE
Peer-to-peer code review by Team #78 - The Hummingbirds  🐦 

### ISSUE THREAD

**Issue by voscarmv** [nriqu322/Restaurant-page#3]
- Nice work. Good job with the background.
- Use `cover` without background repetition for the main page.
- Fix the titles with overlapping top navbar in the other two sections.
- Fix the `100 vh` background from the menu section.
- Make the logo image a redirection link to the main page.
- A good project as well.
- You forgot to add Nigeria, Kossy's country. What's up with that, bro?
- On mobile version, the menu is missing some `padding-bottom`: the last element is touching the bottom of the page. Add footer.

**Comment by nriqu322** [comment]
Thanks for the comments.
